### ISSUE TITLE
compatibility with gitbucket 4.10

### ISSUE THREAD

**Issue by McFoggy** [amuramatsu/gitbucket-rst-plugin#2]
Please consider to adapt to gitbucket 4.10, see [release notes](https://gitbucket.github.io/gitbucket-news/gitbucket/2017/02/25/gitbucket-4.10.html)

**Comment by amuramatsu** [comment]
Thanks for your report.
I'm working to support to support gutbucket 4.10.

**Comment by amuramatsu** [comment]
Release 0.2.0 for compatibility with gitbucket 4.10
