### ISSUE TITLE
compatibility with gitbucket 4.11

### ISSUE THREAD

**Issue by garbagetown** [amuramatsu/gitbucket-rst-plugin#3]
Please consider to adapt to gitbucket 4.11, [see release notes](https://gitbucket.github.io/gitbucket-news/gitbucket/2017/04/01/gitbucket-4.11.html)

**Comment by amuramatsu** [comment]
Something error is happened with gitbucket 4.11?

I use latest version (0.2.1) of this plugin with 4.11, It seemed to working correctly.

**Comment by garbagetown** [comment]
Oh, It sounds good! I'm sorry but I didn't have tried that yet. 

If the plugin supports GitBucket 4.11, I think it would be better to write that in README or somewhere.

Thanks :-)
